# Generated by Django 5.2.4 on 2025-07-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping_data', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SwaggerProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('swagger_url', models.URLField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('swagger_json', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
